### ISSUE TITLE
Сделать свои картинки кофе, допов

### ISSUE THREAD

**Issue by maddenvvs** [office-14/Drinks#15]

**Comment by sofinms** [comment]
В рамках текущей задачи решили картинки хранить в google cloud. Выбрали инструмент google cloud buckets. 
Решил ещё сделать, чтобы можно было обращаться к картинке не только по стандартному url, но и по нашему домену images.office-14.com.
1. Создание бакета. При создании бакета, нужно задать имя бакета и выбрать несколько параметров. Причём имя это глобальное, то есть я так понял среди всех пользователей Google Cloud оно должно быть уникальным.
Выбрал имя images.office-14.com. Там типо можно задать в виде домена, причём вроде нужно подтверждать право на домен (но это не точно).
Далее несколько параметров - тип локации (3 варианта), минимальный срок хранения объектов, тип контроля доступа к объектам (2 варианта - настраиваемый к каждому объекту или на уровне только бакета).
2. Привязка images.office-14.com к созданному бакету.
Эту часть я нагуглил тут - https://deliciousbrains.com/wp-offload-media/doc/how-to-set-up-a-custom-domain-cdn-for-google-cloud-storage/
Там это сделано через Load Balancer

**Comment by sofinms** [comment]
Load balancer решили не использовать и ограничиться https ссылками самого гугла. Установили cache-control каждой картинке на 31 день
