### ISSUE TITLE
Корзина и заказ должны сохраняться в браузере

### ISSUE THREAD

**Issue by maddenvvs** [office-14/Drinks#20]

**Comment by sofinms** [comment]
Имеется в виду тот момент, когда в корзину добавлены товары, затем вкладка (браузер) закрывается. Хотелось бы, чтобы после открытия вкладки, корзина с товарами отобразилась в том же виде.
По заказу аналогично. Но тут нужно учесть момент, что заказ при этом виден только аутентифицированному юзеру.
