### ISSUE TITLE
Добавить long-polling для web-client

### ISSUE THREAD

**Issue by maddenvvs** [office-14/Drinks#22]

**Comment by sofinms** [comment]
Смысл в том, чтобы убрать кнопку "Завершить заказ". Сейчас завершать заказы можно через админку и эта кнопка не нужна. 
В связи с этим нужно на странице заказа:
 -  периодически опрашивать сервер, чтобы узнавать статус заказа;
- если статус изменится на  READY, то отобразить его изменение на странице заказа;
- в случае, если статус заказа READY, добавить кнопку "Очистить", чтобы заказ исчез с этой страницы
