### ISSUE TITLE
Добавить unit/integration тесты в web-client

### ISSUE THREAD

**Issue by maddenvvs** [office-14/Drinks#28]
Также было бы здорово, чтобы эти тесты запускались в TravisCI.

**Comment by sofinms** [comment]
В рамках этой задачи изначально хотел сделать максимальный набор тестов для web client. Но по ходу изучения тестов, понял, что на данном этапе успею только:
- сделать для каждого компонента и сервиса по одному тесту с проверкой на инициализацию объекта;
- заполнить конфиг интеграции Travis CI

**Comment by sofinms** [comment]
В результате немного порефакторил своё приложение. Сложность написания тестов на инициализацию классов компонетнов и сервисов заключалась в том, чтобы написать Mock классы и правильно прописать провайдеры для тестов.
