### ISSUE TITLE
Добавить индикатор загрузки в web-client

### ISSUE THREAD

**Issue by maddenvvs** [office-14/Drinks#38]

**Comment by sofinms** [comment]
Решил внедрить индикатор загрузки в виде полоски, а не в виде круглого спинера, как планировал изначально.
Нужно было сделать, чтобы автоматически при http запросе появлялся loading-bar и при этом можно было его не включать на некоторые запросы (лонг полинг).
Выбрал готовое решение - ngx-loading-bar/http-client, там нужные мне фичи есть.
