### ISSUE TITLE
Посмотреть, где дешевле всего из облаков развернуть наш проект

### ISSUE THREAD

**Issue by maddenvvs** [office-14/Drinks#42]
Есть следующие облака:
- Google Cloud
- Amazon Web Services
- Microsoft Azure

**Comment by sofinms** [comment]
Microsoft Azure - не доступен для регистрации в России
Amazon Web Services - не разобрался с бесплатным периодом
Google Cloud - создан аккаунт
По сути все эти сервисы примерно равны. Нужные нам фичи и возможности (кубернетес, облака и т.д.) есть во всех трёх и цены тоже у всех примерно одинаковые. Google даёт 300$  и 12 месяцев их использования - в этом его преимущество.
